# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ultra"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/mockingbird"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "ultra/packages/leftindust"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "tests"
    schedule:
      interval: "weekly"
 - package-ecosystem: "npm"
    directory: "tests"
    schedule:
      interval: "weekly"
