services:
  icd-api:
    image: whoicd/icd-api
    environment:
      - acceptLicense=true
      - include=2021-05_en
    healthcheck:
      test: "apk add curl; curl -X GET \"http://localhost:80/icd/entity/search?q=aids&flatResults=true\" -H  \"accept: application/json\" -H  \"API-Version: v2\" -H  \"Accept-Language: en\""
      interval: 10s
      timeout: 5s
      retries: 5
  mockingbird-postgres:
    environment:
      POSTGRES_DB: mediq
      POSTGRES_USER: mediq
      POSTGRES_PASSWORD: mediq
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mediq -d mediq" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mockingbird:
    environment:
      - WHO_ICD_API=http://icd-api:80/icd
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mockingbird-postgres:5432/mediq
      - SPRING_DATASOURCE_USERNAME=mediq
      - SPRING_DATASOURCE_PASSWORD=mediq
    build:
      context: .
      dockerfile: mockingbird.Dockerfile
    command: [ "gradle", "mockingbird:integrationTest" ]
    depends_on:
      mockingbird-postgres:
        condition: service_healthy
      icd-api:
        condition: service_healthy