name: Run Gradle on PRs
on: pull_request
jobs:
  mockingbird-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: |
          echo $DEV_ENV_FILE >> mockingbird/src/main/resources/serviceAccountKey.json
      shell: bash
      env:
          DEV_ENV_FILE : ${{secrets.SERVICE_ACCOUNT_KEY}}
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew mockingbird:build
      
    - uses: codecov/codecov-action@v2
      with:
        files: ./mockingbird/build/coverage.xml
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
  ultra-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew ultra:build
