name: Mockingbird
on:
  pull_request:
    paths-ignore:
      - 'mockingbird/**'
    branches:
      - main
jobs:
  build-mockingbird:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
