name: Mockingbird
on:
  pull_request:
    paths: 
      - 'mockingbird/**'
    branches:
      - main
  workflow_dispatch:
      
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mockinbird:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
          echo $DEV_ENV_FILE >> mockingbird/src/main/resources/serviceAccountKey.json
      shell: bash
      env:
          DEV_ENV_FILE : ${{secrets.SERVICE_ACCOUNT_KEY}}
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew mockingbird:build
      
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./mockingbird/build/coverage.xml
