name: Ultra
on:
  pull_request:
    paths-ignore:
      - 'ultra/**'
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: 'echo "No build required"'
