name: Ultra
on:
  push:
    paths-ignore:
      - 'ultra/**'
jobs:
  build:
    strategy:
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: 'echo "No build required"'
